### ISSUE TITLE
遇到两个问题

### ISSUE THREAD

**Issue by semgilo** [ownself/UnitySpriteGPUInstancing#1]
1、通过Graphics.CopyTexture 实际会多一份内存？
2、创建Texture2DArray会有一个比较久的卡顿？这个你也会？如果有，有办法再优化？
3、Texture2Array 要求纹理大大小必须是一样的，但压缩纹理就没办法保证，也会阻碍大面积全批

**Comment by ownself** [comment]
1. 是会多一份内存的，可以在拷贝后将不需要的原贴图卸载掉
2. 创建可能出现的卡顿，我们是通过在Loading阶段进行来规避的
3. 我们最后的办法是Texture2dArray的尺寸创建的较大，例如1024*1024，然后Copy的时候通过自己的Manager逻辑来维护一个偏移坐标，这样一张大图里面实际上多个不同尺寸的小图，这样就可以做到任意尺寸贴图的合批了，这部分的代码由于是后来实现的，可能我没有贴在这里，但实际逻辑并不复杂

**Comment by semgilo** [comment]
> * 是会多一份内存的，可以在拷贝后将不需要的原贴图卸载掉
> * 创建可能出现的卡顿，我们是通过在Loading阶段进行来规避的
> * 我们最后的办法是Texture2dArray的尺寸创建的较大，例如1024*1024，然后Copy的时候通过自己的Manager逻辑来维护一个偏移坐标，这样一张大图里面实际上多个不同尺寸的小图，这样就可以做到任意尺寸贴图的合批了，这部分的代码由于是后来实现的，可能我没有贴在这里，但实际逻辑并不复杂

感谢您的回复，我还是有点小问题
 3.这个你们是创建RGBA这种纹理吗？如果是压缩纹理的话Graphics.CopyTexture就会失败吧？

**Comment by ownself** [comment]
> > * 是会多一份内存的，可以在拷贝后将不需要的原贴图卸载掉
> > * 创建可能出现的卡顿，我们是通过在Loading阶段进行来规避的
> > * 我们最后的办法是Texture2dArray的尺寸创建的较大，例如1024*1024，然后Copy的时候通过自己的Manager逻辑来维护一个偏移坐标，这样一张大图里面实际上多个不同尺寸的小图，这样就可以做到任意尺寸贴图的合批了，这部分的代码由于是后来实现的，可能我没有贴在这里，但实际逻辑并不复杂
> 
> 感谢您的回复，我还是有点小问题  3.这个你们是创建RGBA这种纹理吗？如果是压缩纹理的话Graphics.CopyTexture就会失败吧？

支持压缩格式的，ETC和ASTC都支持的，如果是压缩贴图是直接在GPU上操作的，不回主内存，效率更高，不过需要注意的是，如果是多张贴图拷贝到一张的话，一定要保证格式相同。

**Comment by semgilo** [comment]
> > > * 是会多一份内存的，可以在拷贝后将不需要的原贴图卸载掉
> > > * 创建可能出现的卡顿，我们是通过在Loading阶段进行来规避的
> > > * 我们最后的办法是Texture2dArray的尺寸创建的较大，例如1024*1024，然后Copy的时候通过自己的Manager逻辑来维护一个偏移坐标，这样一张大图里面实际上多个不同尺寸的小图，这样就可以做到任意尺寸贴图的合批了，这部分的代码由于是后来实现的，可能我没有贴在这里，但实际逻辑并不复杂
> > 
> > 
> > 感谢您的回复，我还是有点小问题  3.这个你们是创建RGBA这种纹理吗？如果是压缩纹理的话Graphics.CopyTexture就会失败吧？
> 
> 支持压缩格式的，ETC和ASTC都支持的，如果是压缩贴图是直接在GPU上操作的，不回主内存，效率更高，不过需要注意的是，如果是多张贴图拷贝到一张的话，一定要保证格式相同。

因为我要是拷贝多少不一样大小（并不是指尺寸）它就会提示我错误
```
Graphics.CopyTexture called for entire mipmaps with different memory size (source (RGBA Compressed ASTC6X6 UNorm) is 118336 bytes and destination (RGBA Compressed ASTC6X6 UNorm) is 467856 bytes)
```
所以我有点不太清楚你所说的拷贝到同一张是什么样的操作，或者说你们只是建了一张，而不是一个Array?

**Comment by ownself** [comment]
是Array，是我文章里最后说的那段，你们没有用到可以不用在意。
这个错误像是CopyTexture的用法的问题，你最好写一个单独的示例工程，先跑通了再用在代码里，你可以先看下mipmap的设置是否都一致，不一致拷贝是会有问题的

**Comment by semgilo** [comment]
> 是Array，是我文章里最后说的那段，你们没有用到可以不用在意。 这个错误像是CopyTexture的用法的问题，你最好写一个单独的示例工程，先跑通了再用在代码里，你可以先看下mipmap的设置是否都一致，不一致拷贝是会有问题的

感谢，确实是我使用的问题，我再研究看看
